Repository TheDanielDoyle/DDNSUpdate, pull requests merged in 2020-09, with the labels that each got.

#5 Added hostbuilder with custom configuration and logging support.
  src/DDNSUpdate/DDNSUpdate.csproj
  src/DDNSUpdate/Infrastructure/Hosting/ApplicationHostBuilder.cs
  src/DDNSUpdate/Infrastructure/Hosting/ConfigurationConfigurator.cs
  src/DDNSUpdate/Infrastructure/Hosting/IApplicationHostBuilder.cs
  src/DDNSUpdate/Infrastructure/Hosting/IConfigurationConfigurator.cs
  src/DDNSUpdate/Infrastructure/Hosting/ILoggingConfigurator.cs
  src/DDNSUpdate/Infrastructure/Hosting/LoggingConfigurator.cs
  src/DDNSUpdate/Infrastructure/Hosting/ReturnCode.cs
  src/DDNSUpdate/Program.cs
  src/DDNSUpdate/Properties/launchSettings.json
  src/DDNSUpdate/config.Development.json
  src/DDNSUpdate/config.json
Labels: task

#6 Added DDNSUpdateHostedService
  src/DDNSUpdate/Application/DDNSUpdateHostedService.cs
  src/DDNSUpdate/DDNSUpdate.csproj
  src/DDNSUpdate/Infrastructure/Configuration/ApplicationConfiguration.cs
  src/DDNSUpdate/Infrastructure/ServiceProfiles/ConfigurationServiceProfile.cs
  src/DDNSUpdate/Infrastructure/ServiceProfiles/HostedServiceProfile.cs
  src/DDNSUpdate/config.Development.json
  src/DDNSUpdate/config.json
Labels: task

#16 Update README.md
  README.md
Labels: documentation

#19 Added configuration validation
  src/DDNSUpdate.Tests/ApplicationConfigurationValidationTests.cs
  src/DDNSUpdate.Tests/UnitTest1.cs
  src/DDNSUpdate.Tests/ValidationResultCollectionTests.cs
  src/DDNSUpdate/Application/ApplicationConfigurationValidator.cs
  src/DDNSUpdate/Application/ConfigurationValidator.cs
  src/DDNSUpdate/Application/DDNSUpdateHostedService.cs
  src/DDNSUpdate/Application/IConfigurationValidator.cs
  src/DDNSUpdate/Application/ValidationResultCollection.cs
  src/DDNSUpdate/DDNSUpdate.csproj
  src/DDNSUpdate/Infrastructure/Configuration/ApplicationConfiguration.cs
  src/DDNSUpdate/Infrastructure/ServiceProfiles/ValidationServiceProfile.cs
Labels: task

#22 Task/get external address
  src/DDNSUpdate.Tests/Application/DDNSUpdateInvokerTests.cs
  src/DDNSUpdate.Tests/Application/ExternalAddress/ExternalAddressClientTests.cs
  src/DDNSUpdate.Tests/ApplicationConfigurationValidationTests.cs
  src/DDNSUpdate.Tests/FakeLogger.cs
  src/DDNSUpdate.Tests/ValidationResultCollectionTests.cs
  src/DDNSUpdate/Application/ApplicationConfigurationValidator.cs
  src/DDNSUpdate/Application/Configuration/ApplicationConfigurationValidator.cs
  src/DDNSUpdate/Application/Configuration/ConfigurationValidator.cs
  src/DDNSUpdate/Application/Configuration/IConfigurationValidator.cs
  src/DDNSUpdate/Application/Configuration/ValidationResultCollection.cs
  src/DDNSUpdate/Application/DDNSUpdateInvoker.cs
  src/DDNSUpdate/Application/ExternalAddresses/ExternalAddressClient.cs
  src/DDNSUpdate/Application/ExternalAddresses/ExternalAddressResponse.cs
  src/DDNSUpdate/Application/ExternalAddresses/IExternalAddressClient.cs
  src/DDNSUpdate/Application/ExternalAddresses/IExternalAddressResponse.cs
  src/DDNSUpdate/DDNSUpdate.csproj
  src/DDNSUpdate/Infrastructure/Configuration/ApplicationConfiguration.cs
  src/DDNSUpdate/Infrastructure/Configuration/ExternalAddressProvider.cs
  src/DDNSUpdate/Infrastructure/ServiceProfiles/ExternalAddressProfile.cs
  src/DDNSUpdate/Infrastructure/ServiceProfiles/ValidationServiceProfile.cs
  src/DDNSUpdate/config.Development.json
  src/DDNSUpdate/config.json
Labels: task

#25 Added azure funtion that returns IP address
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider.sln
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider/AzureExternalAddressProvider.csproj
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider/GetIPAddress.cs
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider/Properties/serviceDependencies.json
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider/Properties/serviceDependencies.local.json
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider/host.json
  samples/ExternalAddress/AzureFunction/AzureExternalAddressProvider/local.settings.json
Labels: task

#26 Added YAML application configuration support
  src/DDNSUpdate/DDNSUpdate.csproj
  src/DDNSUpdate/Infrastructure/Hosting/ConfigurationConfigurator.cs
Labels: enhancement
